name: Dependabot PR merge

# read-write repo token
# access to secrets
on:
  workflow_run:
    workflows: ["Node.js CI"]
    types:
      - completed

jobs:
  merge-me:
    name: Merge me!
    if: github.actor == 'dependabot[bot]'

    runs-on: ubuntu-latest

    steps:
      - name: Merge me!
      steps:
        - uses: actions/checkout@v2
        - uses: ahmadnassri/action-dependabot-auto-merge@v2
          with:
            dependency_type: all
            target: minor
            github-token: ${{ secrets.SWAGGER_BOT_GITHUB_TOKEN }}
            update_type: "semver:minor"
